import type { AnalysisResult } from "./types";

export const DEMO_RESULT: AnalysisResult = {
  property: {
    address: "5 Camborne Park, Durham Road",
    postcode: "NE8 4EG",
    bedrooms: 2,
    guests: 4,
  },
  coordinates: { lat: 54.9527, lng: -1.6204 },
  shortLet: {
    annualRevenue: 19167,
    monthlyRevenue: [558, 601, 730, 816, 945, 988, 1074, 1160, 945, 773, 644, 730],
    occupancyRate: 0.58,
    averageDailyRate: 94,
    activeListings: 142,
    comparables: [
      {
        title: "Central Location Gem",
        url: "https://www.airbnb.co.uk/rooms/1",
        bedrooms: 2,
        accommodates: 4,
        averageDailyRate: 89,
        occupancyRate: 0.62,
        annualRevenue: 20146,
        distance: 0.3,
      },
      {
        title: "Executive Accommodation",
        url: "https://www.airbnb.co.uk/rooms/2",
        bedrooms: 2,
        accommodates: 4,
        averageDailyRate: 105,
        occupancyRate: 0.55,
        annualRevenue: 21079,
        distance: 0.5,
      },
      {
        title: "Spacious Family Home",
        url: "https://www.airbnb.co.uk/rooms/3",
        bedrooms: 2,
        accommodates: 5,
        averageDailyRate: 98,
        occupancyRate: 0.60,
        annualRevenue: 21462,
        distance: 0.7,
      },
      {
        title: "Boutique Guest Suite",
        url: "https://www.airbnb.co.uk/rooms/4",
        bedrooms: 2,
        accommodates: 3,
        averageDailyRate: 82,
        occupancyRate: 0.64,
        annualRevenue: 19149,
        distance: 0.4,
      },
      {
        title: "Cosy City Apartment",
        url: "https://www.airbnb.co.uk/rooms/5",
        bedrooms: 2,
        accommodates: 4,
        averageDailyRate: 78,
        occupancyRate: 0.61,
        annualRevenue: 17366,
        distance: 0.6,
      },
      {
        title: "Charming Victorian Flat",
        url: "https://www.airbnb.co.uk/rooms/6",
        bedrooms: 2,
        accommodates: 4,
        averageDailyRate: 91,
        occupancyRate: 0.56,
        annualRevenue: 18594,
        distance: 0.8,
      },
      {
        title: "Stylish Studio Space",
        url: "https://www.airbnb.co.uk/rooms/7",
        bedrooms: 1,
        accommodates: 2,
        averageDailyRate: 72,
        occupancyRate: 0.67,
        annualRevenue: 17605,
        distance: 0.2,
      },
      {
        title: "Modern Urban Retreat",
        url: "https://www.airbnb.co.uk/rooms/8",
        bedrooms: 2,
        accommodates: 4,
        averageDailyRate: 101,
        occupancyRate: 0.53,
        annualRevenue: 19533,
        distance: 1.0,
      },
    ],
  },
  longLet: {
    monthlyRent: 1190,
    estimateHigh: 1350,
    estimateLow: 1050,
    comparables: [
      { address: "Durham Road, Gateshead", rent: 1200, distance: 0.2, bedrooms: 2 },
      { address: "Bensham Road, Gateshead", rent: 1150, distance: 0.5, bedrooms: 2 },
      { address: "Saltwell Road, Gateshead", rent: 1250, distance: 0.8, bedrooms: 2 },
      { address: "Whitehall Road, Gateshead", rent: 1100, distance: 0.6, bedrooms: 2 },
      { address: "Coatsworth Road, Gateshead", rent: 1225, distance: 0.4, bedrooms: 2 },
    ],
  },
  demandDrivers: {
    hospitals: [
      { name: "Queen Elizabeth Hospital", type: "hospital", address: "Sheriff Hill, Gateshead NE9 6SX", distance: 2.1, rating: 4.1 },
    ],
    universities: [
      { name: "Newcastle University", type: "university", address: "Newcastle upon Tyne NE1 7RU", distance: 1.8, rating: 4.5 },
      { name: "Northumbria University", type: "university", address: "Newcastle upon Tyne NE1 8ST", distance: 2.0, rating: 4.3 },
    ],
    airports: [
      { name: "Newcastle International Airport", type: "airport", address: "Woolsington NE13 8BZ", distance: 9.5, rating: 4.0 },
    ],
    trainStations: [
      { name: "Newcastle Central Station", type: "train_station", address: "Neville Street, Newcastle NE1 5DL", distance: 1.5, rating: 4.2 },
      { name: "MetroCentre Station", type: "train_station", address: "Gateshead NE11 9YG", distance: 3.2, rating: 3.8 },
    ],
    busStations: [
      { name: "Gateshead Interchange", type: "bus_station", address: "Gateshead NE8 1BH", distance: 0.8, rating: 3.5 },
    ],
    subwayStations: [
      { name: "Gateshead Metro Station", type: "subway_station", address: "Gateshead NE8 1AE", distance: 0.7, rating: 3.9 },
    ],
  },
  nearbyEvents: {
    events: [
      { name: "The Great Exhibition of the North", date: "2026-04-15", time: "10:00", venue: "BALTIC Centre", category: "Exhibition", genre: "Art", distance: 1.2, url: "#" },
      { name: "Newcastle United vs Sunderland", date: "2026-04-20", time: "15:00", venue: "St James' Park", category: "Sports", genre: "Football", distance: 2.0, url: "#" },
      { name: "Sage Gateshead Concert Series", date: "2026-05-01", time: "19:30", venue: "Sage Gateshead", category: "Music", genre: "Classical", distance: 1.0, url: "#" },
      { name: "Gateshead Food & Drink Festival", date: "2026-05-10", time: "11:00", venue: "Gateshead Quays", category: "Festival", genre: "Food", distance: 1.1, url: "#" },
      { name: "Great North Run", date: "2026-09-13", time: "10:00", venue: "Newcastle to South Shields", category: "Sports", genre: "Running", distance: 0.5, url: "#" },
    ],
    totalEvents: 23,
  },
  financials: {
    shortLetGrossAnnual: 19167,
    shortLetNetAnnual: 9967,
    longLetGrossAnnual: 14280,
    longLetNetAnnual: 12852,
    monthlyDifference: -240,
    annualDifference: -2885,
    breakEvenOccupancy: 0.72,
  },
  risk: {
    incomeVolatility: "moderate",
    setupCost: "moderate",
    regulatory: "low",
    guestDamage: "moderate",
    seasonality: "moderate",
    platformDependency: "high",
    locationDemand: "low",
    competition: "moderate",
    overallScore: 48,
  },
  verdict: {
    fit: "moderate",
    netDifference: -2885,
    riskLevel: "moderate",
    ownerInvolvement: "moderate",
    recommendation:
      "This property shows moderate potential for short-term letting. While the gross revenue is attractive, after accounting for operating costs (cleaning, supplies, platform fees, utilities), the net income is lower than a traditional long-term let. Consider this route if you value flexibility and are willing to actively manage the property or hire a management company.",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
